language: java
sudo: false

jdk:
  - oraclejdk8

script: mvn scoverage:report -B

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/.zinc
  - 2.11/target/scala-2.11.8
  - 2.11/target/analysis

after_success: mvn coveralls:report
