
junit_tests(
  name='zip',
  dependencies=[
    'src/main/scala/org/apache/spark/scheduler/test',
    'src/main/scala/org/hammerlab/magic/rdd/zip',
    'src/main/scala/org/hammerlab/magic/test/spark',
  ],
  sources=globs('*.scala')
)
