
junit_tests(
  name='serde',
  dependencies=[
    'src/main/scala/org/hammerlab/magic/rdd/serde',
    'src/main/scala/org/hammerlab/magic/test',
    'src/main/scala/org/hammerlab/magic/test/rdd',
    'src/main/scala/org/hammerlab/magic/test/version',
    'src/test/scala/org/hammerlab/magic/test/serde/util',
  ],
  sources=globs('*.scala')
)
