
junit_tests(
  name='keyed',
  dependencies=[
    'src/main/scala/org/hammerlab/magic/rdd/keyed',
    'src/main/scala/org/hammerlab/magic/test/rdd',
    'src/main/scala/org/hammerlab/magic/test/spark',
  ],
  sources=globs('*.scala')
)
