
junit_tests(
  name='rdd',
  dependencies=[
    'src/main/scala/org/apache/spark/scheduler/test',
    'src/main/scala/org/hammerlab/magic/rdd',
    'src/main/scala/org/hammerlab/magic/test/rdd',
    'src/main/scala/org/hammerlab/magic/test/spark',
  ],
  sources=globs('*.scala')
)
