
scala_library(
  name='util',
  dependencies=[
    '3rdparty:kryo',
    '3rdparty:spark-core',
    'src/main/scala/org/hammerlab/magic/test/serde',
    'src/main/scala/org/hammerlab/magic/test/spark',
  ],
  sources=globs('*.scala')
)
